# docker-compose.yml
version: '3.3'

services:
    laracom-demo-cli:
      build: ./demo-cli
      environment:
        MICRO_REGISTRY: "etcd"

    laracom-demo-service:
        build: ./demo-service
        ports:
          - 9091:9091
        environment:
          MICRO_SERVER_ADDRESS: ":9091"
          MICRO_REGISTRY: "etcd"
    
    laracom-user-service:
      depends_on:
        - laracom-user-db
      build: ./user-service
      ports:
        - 9092:9091
      environment:
        MICRO_SERVER_ADDRESS: ":9091"
        MICRO_REGISTRY: "etcd"
        DB_HOST: "laracom-user-db:3306"
        DB_NAME: "laracom_user"
        DB_USER: "test"
        DB_PASSWORD: "test"

volumes:
    db_data: {}